### ISSUE TITLE
super speed

### ISSUE THREAD

**Issue by logan001** [ulli-kroll/rtl8814au#2]
new to github ans such.
is there any way to check is driver use superspeed corectly? usb-ac68 seems to have  three-transmit, four-receive and i can't find type in the driver.

**Comment by ulli-kroll** [comment]
I'm lazy ..
please read here
https://github.com/diederikdehaas/rtl8814AU/issues/1

The problem here the wireless stack get disturbed due the disconnect/reconnect on the usb bus.
I have some solution in mind to do this in early init phase.

If you want to test do
`insmod rtl8814au.ko rtw_switch_usb_mode=1`

**Comment by logan001** [comment]
sudo insmod rtl8814au.ko 
gives
insmod: ERROR: could not insert module rtl8814au.ko: Unknown symbol in module

**Comment by ulli-kroll** [comment]
do
```
modprobe mac80211
insmod rtl8814.ko rtw_switch_usb_mode=1
```

**Comment by logan001** [comment]
success
it goes to usb 3.0 with or without that setting
if i can make AP run at 433 mbps as it is on windows...that will be great

**Comment by ulli-kroll** [comment]
> it goes to usb 3.0 with or without that setting

Do a **full** power off or disconnect the device.
This will be the first device which works without this hack.

**Comment by logan001** [comment]
ive done the test with device pluged in after the system was up.
It seems that device will start with usb 3.0 only with the flag for driver.
I guess windows kind of set it to usb 3.0. No idea how this works but ive seen something similar with mac address of my network card.

Edit: 
Driver that i normal use (dkms version from someone else on git) does not work also with usb 3.0. what's funny is that i cant even load the driver with 
`sudo modprobe 8814au`
lsusb -t show the device but Driver=.

Acutally i had the same issue with your driver but make clean/ make /insmod seems to solve the issue even though i had the driver compiled already.
So i'm not even sure i can start the device if i start computer/linux without the device plugged in.
But my knowledge of linux is limited.

**Comment by ulli-kroll** [comment]
> It seems that device will start with usb 3.0 only with the flag for driver.
> I guess windows kind of set it to usb 3.0.

I think the Windows driver does this "on default". 
And IMHO Realtek removed the Windows support files from this driver.

You can boot any linux computer without this deivce plugged in and the driver is loaded.

My talking about **not** to support dkms, or driver install/remove "on default" is because 
a normal user will use this functionality not regarding the state of the driver.
So he doesn't do a previous small test until he enables this in **full**. dkms or other mode.
